id = "zed-chocolate"
name = "Chocolate Theme"
version = "0.0.1"
schema_version = 1
authors = ["Bruno Zalcberg <bruno@zalcberg.me>"]
description = "Chocolate theme for Zed ğŸ«"
repository = "https://github.com/your-name/my-zed-extension"
